spring.application.name=restacontrol
server.port=7070

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/restaurante
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Keep SQL schema management in PostgreSQL scripts
spring.sql.init.mode=never

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
